W1204 21:39:41.171454 2345099 site-packages/torch/distributed/run.py:793] 
W1204 21:39:41.171454 2345099 site-packages/torch/distributed/run.py:793] *****************************************
W1204 21:39:41.171454 2345099 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1204 21:39:41.171454 2345099 site-packages/torch/distributed/run.py:793] *****************************************
WARNING - train - No observers have been added to this run
WARNING - train - No observers have been added to this run
WARNING - train - No observers have been added to this run
WARNING - train - No observers have been added to this run
INFO - train - Running command 'load_config'
INFO - train - Started
INFO - train - Completed after 0:00:00
INFO - train - Running command 'load_config'
INFO - train - Started
INFO - train - Running command 'load_config'
INFO - train - Started
INFO - train - Completed after 0:00:00
INFO - train - Completed after 0:00:00
INFO - train - Running command 'load_config'
INFO - train - Started
INFO - train - Completed after 0:00:00
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py:153: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location='cpu')
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py:153: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location='cpu')
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py:153: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location='cpu')
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py:153: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location='cpu')
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647350383/work/aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647350383/work/aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647350383/work/aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647350383/work/aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[rank1]:[W1204 21:40:18.390461732 reducer.cpp:1400] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank3]:[W1204 21:40:18.544994351 reducer.cpp:1400] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank0]:[W1204 21:40:18.554155531 reducer.cpp:1400] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[rank2]:[W1204 21:40:18.583621725 reducer.cpp:1400] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/trackformer/util/misc.py:106: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = torch.ByteStorage.from_buffer(buffer)
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/trackformer/util/misc.py:106: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = torch.ByteStorage.from_buffer(buffer)
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/trackformer/util/misc.py:106: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = torch.ByteStorage.from_buffer(buffer)
/data/users4/sdeshpande8/DL_Assignements/trackformer/src/trackformer/util/misc.py:106: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = torch.ByteStorage.from_buffer(buffer)
WARNING - submitit - Added new config entry: "obj_detector_model.img_transform"
WARNING - submitit - Added new config entry: "obj_detector_model.model"
WARNING - submitit - Added new config entry: "obj_detector_model.post.bbox"
WARNING - submitit - Changed type of config entry "seed" from int to NoneType
WARNING - submitit - Changed type of config entry "dataset_name" from str to DogmaticList
WARNING - submitit.track - No observers have been added to this run
INFO - submitit.track - Running command 'main'
INFO - submitit.track - Started
WARNING - submitit - Added new config entry: "obj_detector_model.img_transform"
WARNING - submitit - Added new config entry: "obj_detector_model.model"
WARNING - submitit - Added new config entry: "obj_detector_model.post.bbox"
WARNING - submitit - Changed type of config entry "seed" from int to NoneType
WARNING - submitit - Changed type of config entry "dataset_name" from str to DogmaticList
WARNING - submitit.track - No observers have been added to this run
INFO - submitit.track - Running command 'main'
INFO - submitit.track - Started
WARNING - submitit - Added new config entry: "obj_detector_model.img_transform"
WARNING - submitit - Added new config entry: "obj_detector_model.model"
WARNING - submitit - Added new config entry: "obj_detector_model.post.bbox"
WARNING - submitit - Changed type of config entry "seed" from int to NoneType
WARNING - submitit - Changed type of config entry "dataset_name" from str to DogmaticList
WARNING - submitit.track - No observers have been added to this run
INFO - submitit.track - Running command 'main'
INFO - submitit.track - Started
WARNING - submitit - Added new config entry: "obj_detector_model.img_transform"
WARNING - submitit - Added new config entry: "obj_detector_model.model"
WARNING - submitit - Added new config entry: "obj_detector_model.post.bbox"
WARNING - submitit - Changed type of config entry "seed" from int to NoneType
WARNING - submitit - Changed type of config entry "dataset_name" from str to DogmaticList
WARNING - submitit.track - No observers have been added to this run
INFO - submitit.track - Running command 'main'
INFO - submitit.track - Started
ERROR - submitit.track - Failed after 0:00:01!
ERROR - submitit.track - Failed after 0:00:01!
ERROR - submitit.track - Failed after 0:00:01!
[rank1]: Traceback (most recent call last):
[rank1]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py", line 335, in <module>
[rank1]:     train(args)
[rank1]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py", line 282, in train
[rank1]:     val_stats, _ = evaluate(
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/trackformer/engine.py", line 302, in evaluate
[rank1]:     run = ex.run(config_updates=config_updates)
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/experiment.py", line 276, in run
[rank1]:     run()
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/run.py", line 238, in __call__
[rank1]:     self.result = self.main_function(*args)
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
[rank1]:     result = wrapped(*args, **kwargs)
[rank1]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/track.py", line 35, in main
[rank1]:     debugpy.listen(("localhost", 5678))
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/public_api.py", line 31, in wrapper
[rank1]:     return wrapped(*args, **kwargs)
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 143, in debug
[rank1]:     log.reraise_exception("{0}() failed:", func.__name__, level="info")
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 141, in debug
[rank1]:     return func(address, settrace_kwargs, **kwargs)
[rank1]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 262, in listen
[rank1]:     raise RuntimeError(str(endpoints["error"]))
[rank1]: RuntimeError: Can't listen for client connections: [Errno 98] Address already in use
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py", line 335, in <module>
[rank0]:     train(args)
[rank0]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py", line 282, in train
[rank0]:     val_stats, _ = evaluate(
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/trackformer/engine.py", line 302, in evaluate
[rank0]:     run = ex.run(config_updates=config_updates)
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/experiment.py", line 276, in run
[rank0]:     run()
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/run.py", line 238, in __call__
[rank0]:     self.result = self.main_function(*args)
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
[rank0]:     result = wrapped(*args, **kwargs)
[rank0]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/track.py", line 35, in main
[rank0]:     debugpy.listen(("localhost", 5678))
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/public_api.py", line 31, in wrapper
[rank0]:     return wrapped(*args, **kwargs)
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 143, in debug
[rank0]:     log.reraise_exception("{0}() failed:", func.__name__, level="info")
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 141, in debug
[rank0]:     return func(address, settrace_kwargs, **kwargs)
[rank0]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 262, in listen
[rank0]:     raise RuntimeError(str(endpoints["error"]))
[rank0]: RuntimeError: Can't listen for client connections: [Errno 98] Address already in use
[rank3]: Traceback (most recent call last):
[rank3]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py", line 335, in <module>
[rank3]:     train(args)
[rank3]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/train.py", line 282, in train
[rank3]:     val_stats, _ = evaluate(
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank3]:     return func(*args, **kwargs)
[rank3]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/trackformer/engine.py", line 302, in evaluate
[rank3]:     run = ex.run(config_updates=config_updates)
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/experiment.py", line 276, in run
[rank3]:     run()
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/run.py", line 238, in __call__
[rank3]:     self.result = self.main_function(*args)
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
[rank3]:     result = wrapped(*args, **kwargs)
[rank3]:   File "/data/users4/sdeshpande8/DL_Assignements/trackformer/src/track.py", line 35, in main
[rank3]:     debugpy.listen(("localhost", 5678))
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/public_api.py", line 31, in wrapper
[rank3]:     return wrapped(*args, **kwargs)
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 143, in debug
[rank3]:     log.reraise_exception("{0}() failed:", func.__name__, level="info")
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 141, in debug
[rank3]:     return func(address, settrace_kwargs, **kwargs)
[rank3]:   File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/debugpy/server/api.py", line 262, in listen
[rank3]:     raise RuntimeError(str(endpoints["error"]))
[rank3]: RuntimeError: Can't listen for client connections: [Errno 98] Address already in use
[rank0]:[W1204 21:53:40.888673020 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1204 21:53:42.251171 2345099 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2345124 closing signal SIGTERM
W1204 21:53:42.252653 2345099 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2345125 closing signal SIGTERM
W1204 21:53:42.252799 2345099 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2345126 closing signal SIGTERM
E1204 21:53:42.793867 2345099 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 3 (pid: 2345127) of binary: /home/users/sdeshpande8/anaconda3/envs/trackformer/bin/python
Traceback (most recent call last):
  File "/home/users/sdeshpande8/anaconda3/envs/trackformer/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.5.1', 'console_scripts', 'torchrun')())
  File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/users/sdeshpande8/anaconda3/envs/trackformer/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-04_21:53:42
  host      : arctrddgxa001
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2345127)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
